language: objective-c
matrix:
  fast_finish: true

before_install:
  - brew tap AdoptOpenJDK/homebrew-openjdk
  - brew install --cask adoptopenjdk8
  - export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
  - wget https://apache.mirror.colo-serv.net//ant/binaries/apache-ant-1.10.9-bin.zip
  - unzip apache-ant-1.10.9-bin.zip
  - export PATH=$PWD/apache-ant-1.10.9/bin/:$PATH
  - echo $PATH
  - wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
  - unzip android-sdk_r24.4.1-macosx.zip
  - export ANDROID_HOME=$PWD/android-sdk-macosx
  - export PATH=$PATH:$ANDROID_HOME/tools
  - ( sleep 1 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --all --no-ui --filter platform-tool,android-19,sysimg-19,build-tools-19.1.0,extra-android-support,sys-img-armeabi-v7a-android-19

before_script:
  - android update project -t android-19 -p android/.

script:
  - make

before_deploy:
  - mv build/AirTestFairy.ane build/TestFairySDK-${TRAVIS_TAG}.ane

deploy:
  provider: releases
  api_key:
    secure: XKsQDsEhO3EbKE58KUa4t7lejbZDnNPe1HnRdXPzl7EnPLt7HAVCr2w7uaQaFlIDbzb+7yuPx3z0mc//x1efH5ihF8LJ2oD0p3JOsZXq29AvQloO7V2RqxloHIXmzueH1StnVnI1vwdKaF2g1RhmuX7TBufLex+SzdZZTdpE0vc=
  file: build/TestFairySDK-${TRAVIS_TAG}.ane
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
